USE AK;
SHOW TABLES;
-- Inner Join : Joins on behalf of common records
-- Left Join : All records from left table(first table of query) & matching records from right table(else NULL filled)
-- Right Join : Vice-versa of Left Join
-- Full Outer Join : Can be Assumed as UNION of two tables
-- Self Join : 

SELECT * FROM CUSTOMERS
CROSS JOIN EMPL;

SELECT E.FIRSTNAME,S.ADDRESS
FROM STUDENT AS S
INNER JOIN EMPL AS E
ON E.EMPID=S.ROLLNO;

SELECT S.ADDRESS,e.FIRSTNAME
FROM STUDENT AS S
LEFT JOIN EMPL AS E
ON E.EMPID=S.ROLLNO;

SELECT S.ADDRESS,e.FIRSTNAME
FROM STUDENT S
RIGHT JOIN EMPL E
ON E.EMPID=S.ROLLNO;

SELECT ADDRESS,FIRSTNAME
FROM STUDENT
FULL JOIN EMPL
ON EMPID=ROLLNO;

SELECT S.ADDRESS,e.FIRSTNAME
FROM STUDENT S
CROSS JOIN EMPL E
ON E.EMPID=S.ROLLNO;

-- x -- x -- x -- x -- x -- x -- x --

-- Self Join 👇
SELECT S1.NAME,S2.NAME,S1.ADDRESS
FROM STUDENT S1,STUDENT S2
WHERE S1.ROLLNO <> S2.ROLLNO
AND S1.ADDRESS=S2.ADDRESS;

SELECT S1.NAME,S2.NAME,S1.ADDRESS
FROM STUDENT S1
JOIN STUDENT S2
ON S1.ADDRESS=S2.ADDRESS;

-- x -- x -- x -- x -- x -- 

SELECT * FROM EMPL;
SELECT * FROM STUDENT;

INSERT INTO EMPL VALUES (7,"DICKERSON","ROSS",40);