USE ak;

SELECT * FROM STUDENT;

CREATE OR REPLACE VIEW stud_view AS 
SELECT NAME,ADDRESS FROM STUDENT 
WHERE ROLLNO > 3;

SELECT * FROM stud_view;

CREATE INDEX idx_name ON STUDENT(ROLLNO,NAME);
SELECT * FROM idx_name;